[
{
  "fields": {
    "exception_type": "DataError",
    "sanitized_traceback": "Traceback (most recent call last):\n  File \"python2.7/site-packages/django/core/handlers/base.py\", line 112, in get_response\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n  File \"python2.7/site-packages/django/db/transaction.py\", line 371, in inner\n    return func(*args, **kwargs)\n  File \"python2.7/site-packages/django/contrib/admin/options.py\", line 465, in wrapper\n    return self.admin_site.admin_view(view)(*args, **kwargs)\n  File \"python2.7/site-packages/django/utils/decorators.py\", line 99, in _wrapped_view\n    response = view_func(request, *args, **kwargs)\n  File \"python2.7/site-packages/django/views/decorators/cache.py\", line 52, in _wrapped_view_func\n    response = view_func(request, *args, **kwargs)\n  File \"python2.7/site-packages/django/contrib/admin/sites.py\", line 198, in inner\n    return view(request, *args, **kwargs)\n  File \"python2.7/site-packages/django/utils/decorators.py\", line 29, in _wrapper\n    return bound_func(*args, **kwargs)\n  File \"python2.7/site-packages/django/utils/decorators.py\", line 99, in _wrapped_view\n    response = view_func(request, *args, **kwargs)\n  File \"python2.7/site-packages/django/utils/decorators.py\", line 25, in bound_func\n    return func(self, *args2, **kwargs2)\n  File \"python2.7/site-packages/django/db/transaction.py\", line 371, in inner\n    return func(*args, **kwargs)\n  File \"python2.7/site-packages/django/contrib/admin/options.py\", line 1264, in change_view\n    self.save_related(request, form, formsets, True)\n  File \"python2.7/site-packages/django/contrib/admin/options.py\", line 917, in save_related\n    self.save_formset(request, form, formset, change=change)\n  File \"python2.7/site-packages/django/contrib/admin/options.py\", line 905, in save_formset\n    formset.save()\n  File \"python2.7/site-packages/django/forms/models.py\", line 618, in save\n    return self.save_existing_objects(commit) + self.save_new_objects(commit)\n  File \"python2.7/site-packages/django/forms/models.py\", line 747, in save_new_objects\n    self.new_objects.append(self.save_new(form, commit=commit))\n  File \"python2.7/site-packages/django/forms/models.py\", line 877, in save_new\n    obj.save()\n  File \"python2.7/site-packages/django/db/models/base.py\", line 545, in save\n    force_update=force_update, update_fields=update_fields)\n  File \"python2.7/site-packages/django/db/models/base.py\", line 573, in save_base\n    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)\n  File \"python2.7/site-packages/django/db/models/base.py\", line 654, in _save_table\n    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)\n  File \"python2.7/site-packages/django/db/models/base.py\", line 687, in _do_insert\n    using=using, raw=raw)\n  File \"python2.7/site-packages/django/db/models/manager.py\", line 232, in _insert\n    return insert_query(self.model, objs, fields, **kwargs)\n  File \"python2.7/site-packages/django/db/models/query.py\", line 1514, in insert_query\n    return query.get_compiler(using=using).execute_sql(return_id)\n  File \"python2.7/site-packages/django/db/models/sql/compiler.py\", line 903, in execute_sql\n    cursor.execute(sql, params)\n  File \"python2.7/site-packages/django/db/backends/util.py\", line 53, in execute\n    return self.cursor.execute(sql, params)\n  File \"python2.7/site-packages/django/db/utils.py\", line 99, in __exit__\n    six.reraise(dj_exc_type, dj_exc_value, traceback)\n  File \"python2.7/site-packages/django/db/backends/util.py\", line 53, in execute\n    return self.cursor.execute(sql, params)\nDataError: value too long for type character varying(100)",
    "error_message": "value too long for type character varying(100)",
    "django_version": "1.6",
    "traceback": "Traceback (most recent call last):\r\n\r\n  File \"/apps/appname/env/local/lib/python2.7/site-packages/django/core/handlers/base.py\", line 112, in get_response\r\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\r\n\r\n  File \"/apps/appname/env/local/lib/python2.7/site-packages/django/db/transaction.py\", line 371, in inner\r\n    return func(*args, **kwargs)\r\n\r\n  File \"/apps/appname/env/local/lib/python2.7/site-packages/django/contrib/admin/options.py\", line 465, in wrapper\r\n    return self.admin_site.admin_view(view)(*args, **kwargs)\r\n\r\n  File \"/apps/appname/env/local/lib/python2.7/site-packages/django/utils/decorators.py\", line 99, in _wrapped_view\r\n    response = view_func(request, *args, **kwargs)\r\n\r\n  File \"/apps/appname/env/local/lib/python2.7/site-packages/django/views/decorators/cache.py\", line 52, in _wrapped_view_func\r\n    response = view_func(request, *args, **kwargs)\r\n\r\n  File \"/apps/appname/env/local/lib/python2.7/site-packages/django/contrib/admin/sites.py\", line 198, in inner\r\n    return view(request, *args, **kwargs)\r\n\r\n  File \"/apps/appname/env/local/lib/python2.7/site-packages/django/utils/decorators.py\", line 29, in _wrapper\r\n    return bound_func(*args, **kwargs)\r\n\r\n  File \"/apps/appname/env/local/lib/python2.7/site-packages/django/utils/decorators.py\", line 99, in _wrapped_view\r\n    response = view_func(request, *args, **kwargs)\r\n\r\n  File \"/apps/appname/env/local/lib/python2.7/site-packages/django/utils/decorators.py\", line 25, in bound_func\r\n    return func(self, *args2, **kwargs2)\r\n\r\n  File \"/apps/appname/env/local/lib/python2.7/site-packages/django/db/transaction.py\", line 371, in inner\r\n    return func(*args, **kwargs)\r\n\r\n  File \"/apps/appname/env/local/lib/python2.7/site-packages/django/contrib/admin/options.py\", line 1264, in change_view\r\n    self.save_related(request, form, formsets, True)\r\n\r\n  File \"/apps/appname/env/local/lib/python2.7/site-packages/django/contrib/admin/options.py\", line 917, in save_related\r\n    self.save_formset(request, form, formset, change=change)\r\n\r\n  File \"/apps/appname/env/local/lib/python2.7/site-packages/django/contrib/admin/options.py\", line 905, in save_formset\r\n    formset.save()\r\n\r\n  File \"/apps/appname/env/local/lib/python2.7/site-packages/django/forms/models.py\", line 618, in save\r\n    return self.save_existing_objects(commit) + self.save_new_objects(commit)\r\n\r\n  File \"/apps/appname/env/local/lib/python2.7/site-packages/django/forms/models.py\", line 747, in save_new_objects\r\n    self.new_objects.append(self.save_new(form, commit=commit))\r\n\r\n  File \"/apps/appname/env/local/lib/python2.7/site-packages/django/forms/models.py\", line 877, in save_new\r\n    obj.save()\r\n\r\n  File \"/apps/appname/env/local/lib/python2.7/site-packages/django/db/models/base.py\", line 545, in save\r\n    force_update=force_update, update_fields=update_fields)\r\n\r\n  File \"/apps/appname/env/local/lib/python2.7/site-packages/django/db/models/base.py\", line 573, in save_base\r\n    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)\r\n\r\n  File \"/apps/appname/env/local/lib/python2.7/site-packages/django/db/models/base.py\", line 654, in _save_table\r\n    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)\r\n\r\n  File \"/apps/appname/env/local/lib/python2.7/site-packages/django/db/models/base.py\", line 687, in _do_insert\r\n    using=using, raw=raw)\r\n\r\n  File \"/apps/appname/env/local/lib/python2.7/site-packages/django/db/models/manager.py\", line 232, in _insert\r\n    return insert_query(self.model, objs, fields, **kwargs)\r\n\r\n  File \"/apps/appname/env/local/lib/python2.7/site-packages/django/db/models/query.py\", line 1514, in insert_query\r\n    return query.get_compiler(using=using).execute_sql(return_id)\r\n\r\n  File \"/apps/appname/env/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py\", line 903, in execute_sql\r\n    cursor.execute(sql, params)\r\n\r\n  File \"/apps/appname/env/local/lib/python2.7/site-packages/django/db/backends/util.py\", line 53, in execute\r\n    return self.cursor.execute(sql, params)\r\n\r\n  File \"/apps/appname/env/local/lib/python2.7/site-packages/django/db/utils.py\", line 99, in __exit__\r\n    six.reraise(dj_exc_type, dj_exc_value, traceback)\r\n\r\n  File \"/apps/appname/env/local/lib/python2.7/site-packages/django/db/backends/util.py\", line 53, in execute\r\n    return self.cursor.execute(sql, params)\r\n\r\nDataError: value too long for type character varying(100)"
  },
  "model": "error_posts.errorpost",
  "pk": 1
},
{
  "fields": {
    "exception_type": "ValueError",
    "sanitized_traceback": "Traceback (most recent call last):\n  File \"python2.7/site-packages/django/core/handlers/base.py\", line 111, in get_response\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n  File \"python2.7/site-packages/django/views/generic/base.py\", line 69, in view\n    return self.dispatch(request, *args, **kwargs)\n  File \"python2.7/site-packages/braces/views/_access.py\", line 64, in dispatch\n    request, *args, **kwargs)\n  File \"python2.7/site-packages/django/views/generic/base.py\", line 87, in dispatch\n    return handler(request, *args, **kwargs)\n  File \"python2.7/site-packages/django/views/generic/edit.py\", line 207, in post\n    return super(BaseCreateView, self).post(request, *args, **kwargs)\n  File \"python2.7/site-packages/django/views/generic/edit.py\", line 173, in post\n    return self.form_valid(form)\n  File \"?????.py\", line ??, in ??????\n    ????????\n  File \"python2.7/site-packages/django/db/models/base.py\", line 589, in save\n    force_update=force_update, update_fields=update_fields)\n  File \"python2.7/site-packages/django/db/models/base.py\", line 626, in save_base\n    update_fields=update_fields, raw=raw, using=using)\n  File \"python2.7/site-packages/django/dispatch/dispatcher.py\", line 198, in send\n    response = receiver(signal=self, sender=sender, **named)\n  File \"?????.py\", line ??, in ??????\n    ????????\n  File \"?????.py\", line ??, in ??????\n    ????????\n  File \"?????.py\", line ??, in ??????\n    ????????\n  File \"python2.7/site-packages/templated_email/__init__.py\", line 74, in send_templated_mail\n    headers=headers, **kwargs)\n  File \"python2.7/site-packages/templated_email/backends/vanilla_django.py\", line 184, in send\n    e.send(fail_silently)\n  File \"python2.7/site-packages/django/core/mail/message.py\", line 286, in send\n    return self.get_connection(fail_silently).send_messages([self])\n  File \"python2.7/site-packages/django/core/mail/backends/smtp.py\", line 99, in send_messages\n    sent = self._send(message)\n  File \"python2.7/site-packages/django/core/mail/backends/smtp.py\", line 112, in _send\n    for addr in email_message.recipients()]\n  File \"python2.7/site-packages/django/core/mail/message.py\", line 105, in sanitize_address\n    nm, addr = addr\nValueError: too many values to unpack",
    "error_message": "too many values to unpack",
    "django_version": "1.7",
    "traceback": "Traceback (most recent call last):\r\n  File \"/app/server/python/lib/python2.7/site-packages/django/core/handlers/base.py\", line 111, in get_response\r\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\r\n  File \"/app/server/python/lib/python2.7/site-packages/django/views/generic/base.py\", line 69, in view\r\n    return self.dispatch(request, *args, **kwargs)\r\n  File \"/app/server/python/lib/python2.7/site-packages/braces/views/_access.py\", line 64, in dispatch\r\n    request, *args, **kwargs)\r\n  File \"/app/server/python/lib/python2.7/site-packages/django/views/generic/base.py\", line 87, in dispatch\r\n    return handler(request, *args, **kwargs)\r\n  File \"/app/server/python/lib/python2.7/site-packages/django/views/generic/edit.py\", line 207, in post\r\n    return super(BaseCreateView, self).post(request, *args, **kwargs)\r\n  File \"/app/server/python/lib/python2.7/site-packages/django/views/generic/edit.py\", line 173, in post\r\n    return self.form_valid(form)\r\n  File \"/app/customapp/views.py\", line 62, in form_valid\r\n    self.object.save()\r\n  File \"/app/server/python/lib/python2.7/site-packages/django/db/models/base.py\", line 589, in save\r\n    force_update=force_update, update_fields=update_fields)\r\n  File \"/app/server/python/lib/python2.7/site-packages/django/db/models/base.py\", line 626, in save_base\r\n    update_fields=update_fields, raw=raw, using=using)\r\n  File \"/app/server/python/lib/python2.7/site-packages/django/dispatch/dispatcher.py\", line 198, in send\r\n    response = receiver(signal=self, sender=sender, **named)\r\n  File \"/app/customapp/signal_receivers.py\", line 22, in send_new_shipment_email\r\n    emails.send_shipment_email_to_all_nvocc(instance)\r\n  File \"/app/customapp/emails.py\", line 30, in send_shipment_email_to_all_nvocc\r\n    context={})\r\n  File \"/app/core/mail_utils.py\", line 15, in send_templated_mail\r\n    return templated_email.send_templated_mail(*args, **kwargs)\r\n  File \"/app/server/python/lib/python2.7/site-packages/templated_email/__init__.py\", line 74, in send_templated_mail\r\n    headers=headers, **kwargs)\r\n  File \"/app/server/python/lib/python2.7/site-packages/templated_email/backends/vanilla_django.py\", line 184, in send\r\n    e.send(fail_silently)\r\n  File \"/app/server/python/lib/python2.7/site-packages/django/core/mail/message.py\", line 286, in send\r\n    return self.get_connection(fail_silently).send_messages([self])\r\n  File \"/app/server/python/lib/python2.7/site-packages/django/core/mail/backends/smtp.py\", line 99, in send_messages\r\n    sent = self._send(message)\r\n  File \"/app/server/python/lib/python2.7/site-packages/django/core/mail/backends/smtp.py\", line 112, in _send\r\n    for addr in email_message.recipients()]\r\n  File \"/app/server/python/lib/python2.7/site-packages/django/core/mail/message.py\", line 105, in sanitize_address\r\n    nm, addr = addr\r\nValueError: too many values to unpack"
  },
  "model": "error_posts.errorpost",
  "pk": 2
}
]
