[{"fields": {"exception_type": "DataError", "error_message": "value too long for type character varying(100)", "django_version": "1.6", "traceback": "Traceback (most recent call last):\r\n\r\n  File \"/apps/appname/env/local/lib/python2.7/site-packages/django/core/handlers/base.py\", line 112, in get_response\r\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\r\n\r\n  File \"/apps/appname/env/local/lib/python2.7/site-packages/django/db/transaction.py\", line 371, in inner\r\n    return func(*args, **kwargs)\r\n\r\n  File \"/apps/appname/env/local/lib/python2.7/site-packages/django/contrib/admin/options.py\", line 465, in wrapper\r\n    return self.admin_site.admin_view(view)(*args, **kwargs)\r\n\r\n  File \"/apps/appname/env/local/lib/python2.7/site-packages/django/utils/decorators.py\", line 99, in _wrapped_view\r\n    response = view_func(request, *args, **kwargs)\r\n\r\n  File \"/apps/appname/env/local/lib/python2.7/site-packages/django/views/decorators/cache.py\", line 52, in _wrapped_view_func\r\n    response = view_func(request, *args, **kwargs)\r\n\r\n  File \"/apps/appname/env/local/lib/python2.7/site-packages/django/contrib/admin/sites.py\", line 198, in inner\r\n    return view(request, *args, **kwargs)\r\n\r\n  File \"/apps/appname/env/local/lib/python2.7/site-packages/django/utils/decorators.py\", line 29, in _wrapper\r\n    return bound_func(*args, **kwargs)\r\n\r\n  File \"/apps/appname/env/local/lib/python2.7/site-packages/django/utils/decorators.py\", line 99, in _wrapped_view\r\n    response = view_func(request, *args, **kwargs)\r\n\r\n  File \"/apps/appname/env/local/lib/python2.7/site-packages/django/utils/decorators.py\", line 25, in bound_func\r\n    return func(self, *args2, **kwargs2)\r\n\r\n  File \"/apps/appname/env/local/lib/python2.7/site-packages/django/db/transaction.py\", line 371, in inner\r\n    return func(*args, **kwargs)\r\n\r\n  File \"/apps/appname/env/local/lib/python2.7/site-packages/django/contrib/admin/options.py\", line 1264, in change_view\r\n    self.save_related(request, form, formsets, True)\r\n\r\n  File \"/apps/appname/env/local/lib/python2.7/site-packages/django/contrib/admin/options.py\", line 917, in save_related\r\n    self.save_formset(request, form, formset, change=change)\r\n\r\n  File \"/apps/appname/env/local/lib/python2.7/site-packages/django/contrib/admin/options.py\", line 905, in save_formset\r\n    formset.save()\r\n\r\n  File \"/apps/appname/env/local/lib/python2.7/site-packages/django/forms/models.py\", line 618, in save\r\n    return self.save_existing_objects(commit) + self.save_new_objects(commit)\r\n\r\n  File \"/apps/appname/env/local/lib/python2.7/site-packages/django/forms/models.py\", line 747, in save_new_objects\r\n    self.new_objects.append(self.save_new(form, commit=commit))\r\n\r\n  File \"/apps/appname/env/local/lib/python2.7/site-packages/django/forms/models.py\", line 877, in save_new\r\n    obj.save()\r\n\r\n  File \"/apps/appname/env/local/lib/python2.7/site-packages/django/db/models/base.py\", line 545, in save\r\n    force_update=force_update, update_fields=update_fields)\r\n\r\n  File \"/apps/appname/env/local/lib/python2.7/site-packages/django/db/models/base.py\", line 573, in save_base\r\n    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)\r\n\r\n  File \"/apps/appname/env/local/lib/python2.7/site-packages/django/db/models/base.py\", line 654, in _save_table\r\n    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)\r\n\r\n  File \"/apps/appname/env/local/lib/python2.7/site-packages/django/db/models/base.py\", line 687, in _do_insert\r\n    using=using, raw=raw)\r\n\r\n  File \"/apps/appname/env/local/lib/python2.7/site-packages/django/db/models/manager.py\", line 232, in _insert\r\n    return insert_query(self.model, objs, fields, **kwargs)\r\n\r\n  File \"/apps/appname/env/local/lib/python2.7/site-packages/django/db/models/query.py\", line 1514, in insert_query\r\n    return query.get_compiler(using=using).execute_sql(return_id)\r\n\r\n  File \"/apps/appname/env/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py\", line 903, in execute_sql\r\n    cursor.execute(sql, params)\r\n\r\n  File \"/apps/appname/env/local/lib/python2.7/site-packages/django/db/backends/util.py\", line 53, in execute\r\n    return self.cursor.execute(sql, params)\r\n\r\n  File \"/apps/appname/env/local/lib/python2.7/site-packages/django/db/utils.py\", line 99, in __exit__\r\n    six.reraise(dj_exc_type, dj_exc_value, traceback)\r\n\r\n  File \"/apps/appname/env/local/lib/python2.7/site-packages/django/db/backends/util.py\", line 53, in execute\r\n    return self.cursor.execute(sql, params)\r\n\r\nDataError: value too long for type character varying(100)"}, "model": "error_posts.errorpost", "pk": 1}]